## [NumPy](http://www.numpy.org/)

A NumPy egy alacsony szintű matematikai csomag, numerikus számításokhoz.

- Alapvető adatszerkezete az [n dimenziós tömb](https://docs.scipy.org/doc/numpy/reference/arrays.ndarray.html).
- C nyelven íródott. A szokásos tömbműveletek hatékonyan vannak benne megvalósítva.
- Többek között tartalmaz lineáris algebrai és véletlenszám generáló almodult.
- Számos magasabb szintű csomag (pl. scipy, matplotlib, pandas, scikit-learn) épül rá.

A NumPy külső csomag, a telepítésére többféle lehetőség van, például:
- `pip install numpy --user`
- `sudo apt-get install python3-numpy`
- `conda install numpy`

In [3]:
# A NumPy modul importálása np néven.
import numpy as np

In [2]:
# Verzió lekérdezése.
np.__version__

'1.19.5'

#### Tömbök létrehozása

In [3]:
# 1 dimenziós, egész számokból álló tömb létrehozása.
a = np.array([2, 3, 4])

In [4]:
a

array([2, 3, 4])

In [5]:
# A tömb objektum típusa.
type(a)

numpy.ndarray

In [6]:
# Hány dimenziós a tömb?
a.ndim

1

In [7]:
# A dimenziók mérete.
a.shape

(3,)

In [8]:
# Az elemek típusának lekérdezése.
# A NumPy tömbök homogének (kivéve az objektumtömböt).
a.dtype

dtype('int64')

In [16]:
# 2 dimenziós, lebegőpontos tömb létrehozása.
b = np.array([[2.0, 3.0, 4.0], [5.5, 6.6, 7.7]])

In [15]:
b

array([[2. , 3. , 4. ],
       [5.5, 6.6, 7.7]])

In [13]:
# Dimenziók száma, mérete, az elemek típusa.
print(b.ndim)
print(b.shape)
print(b.dtype)

2
(2, 3)
float64


In [17]:
# Az elemek adattípusának beállítása, 1. példa.
np.array([3, 4, 5, 6], dtype='uint8')

array([3, 4, 5, 6], dtype=uint8)

In [18]:
# Az elemek adattípusának beállítása, 2. példa.
np.array([3.3, 4.4], dtype='float32')

array([3.3, 4.4], dtype=float32)

In [21]:
# Tömb betöltése szövegfájlból.
np.genfromtxt('matrix.txt')

array([[0., 1., 1., 0., 1., 0., 1., 1., 0., 1.],
       [0., 0., 1., 0., 1., 1., 0., 1., 0., 1.],
       [0., 0., 1., 0., 0., 0., 1., 1., 0., 0.],
       [0., 1., 0., 0., 1., 0., 1., 1., 0., 0.],
       [1., 0., 1., 1., 0., 0., 1., 0., 1., 1.],
       [1., 0., 1., 0., 0., 1., 1., 0., 1., 0.],
       [1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
       [0., 0., 0., 0., 0., 1., 0., 1., 0., 1.],
       [1., 1., 0., 1., 0., 1., 1., 1., 0., 0.],
       [1., 0., 1., 0., 1., 0., 0., 1., 0., 1.]])

In [22]:
# Nullákból álló tömb létrehozása, 1. példa.
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [24]:
# Nullákból álló tömb létrehozása, 2. példa.
np.zeros((3, 2), dtype='int16')

array([[0, 0],
       [0, 0],
       [0, 0]], dtype=int16)

In [25]:
# Egyesekből álló tömb létrehozása, 1. példa.
np.ones(7, dtype='uint32')

array([1, 1, 1, 1, 1, 1, 1], dtype=uint32)

In [26]:
# Egyesekből álló tömb létrehozása, 2. példa.
np.ones((2, 2, 2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [27]:
# Egységmátrix létrehozása.
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [28]:
# Értéktartomány létrehozása a lépésköz megadásával.
np.arange(0, 2, 0.4)

array([0. , 0.4, 0.8, 1.2, 1.6])

In [30]:
# Értéktartomány létrehozása az elemszám megadásával.
np.linspace(-1, 2, 7)

array([-1. , -0.5,  0. ,  0.5,  1. ,  1.5,  2. ])

In [32]:
# Vektorok összefűzése.
a = np.array([2, 3])
b = np.array([4, 5, 6])
np.concatenate([a, b])

array([2, 3, 4, 5, 6])

In [34]:
# Mátrixok összefűzése vízszintesen.
a = np.array([[2, 3, 4],
              [5, 6, 7]])
np.hstack([a, a])

array([[2, 3, 4, 2, 3, 4],
       [5, 6, 7, 5, 6, 7]])

In [35]:
# Mátrixok összefűzése függőlegesen.
np.vstack([a, a, a])

array([[2, 3, 4],
       [5, 6, 7],
       [2, 3, 4],
       [5, 6, 7],
       [2, 3, 4],
       [5, 6, 7]])

#### Elemek és résztömbök

In [4]:
# Hozzunk létre egy példamátrixot!
a = np.array([[3, 4, 5],
              [6, 7, 8]])

In [39]:
# Elem kiválasztása (az indexelés 0-tól indul).
a[0, 1] # 0. sor, 1. oszlop

4

In [40]:
a[(0, 1)]

4

In [42]:
# ...a háttérben ez történik:
np.ndarray.__getitem__(a, (0, 1))

4

In [43]:
# Teljes sor kiválasztása.
a[1, :]

array([6, 7, 8])

In [44]:
# Így is lehetne.
a[1]

array([6, 7, 8])

In [45]:
# A kiválasztott sor egy 1 dimenziós tömb.
a[1].ndim

1

In [46]:
# Oszlop kiválasztása.
a[:, 2]

array([5, 8])

In [47]:
# Résztömb kiválasztása.
a[:, :-1]

array([[3, 4],
       [6, 7]])

In [48]:
# Adott indexű oszlopok kiválasztása.
a[:, [1, 0, 1]]

array([[4, 3, 4],
       [7, 6, 7]])

In [51]:
# Elemek kiválasztása logikai feltétel alapján.
# (Az eredmény 1 dimenziós.)
a[a % 2 == 0]

array([4, 6, 8])

In [52]:
# A tömb elemei módosíthatók.
a[0, 0] = 100
a

array([[100,   4,   5],
       [  6,   7,   8]])

In [53]:
# Oszlop módosítása.
a[:, 1] = [20, 30]
a

array([[100,  20,   5],
       [  6,  30,   8]])

#### Tömbműveletek

In [54]:
# Hozzunk létre 2 példatömböt!
a = np.array([[1, 2 ,3],
              [4, 5, 6]])
b = np.array([[1, 1, 1],
              [2, 2, 2]])

In [55]:
# Elemenkénti összeadás.
a + b

array([[2, 3, 4],
       [6, 7, 8]])

In [56]:
# Elemenkénti kivonás.
a - b

array([[0, 1, 2],
       [2, 3, 4]])

In [57]:
# Elemenkénti szorzás.
a * b

array([[ 1,  2,  3],
       [ 8, 10, 12]])

In [58]:
# Elemenkénti osztás.
a / b

array([[1. , 2. , 3. ],
       [2. , 2.5, 3. ]])

In [59]:
# Elemenkénti egészosztás.
a // b

array([[1, 2, 3],
       [2, 2, 3]])

In [60]:
# Elemenkénti hatványozás.
a**b

array([[ 1,  2,  3],
       [16, 25, 36]])

In [61]:
# A művelet nem feltétlenül végezhető el.
np.array([2, 3, 4]) + np.array([5, 6])

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [62]:
# Jelenítsük meg újra az "a" tömböt!
a

array([[1, 2, 3],
       [4, 5, 6]])

In [63]:
# Elemenkénti függvények (exp, log, sin, cos, ...).
np.exp(a)

array([[  2.71828183,   7.3890561 ,  20.08553692],
       [ 54.59815003, 148.4131591 , 403.42879349]])

In [64]:
np.sin(a)

array([[ 0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ]])

In [65]:
# Statisztikai műveletek (min, max, sum, mean, std).
a.min()

1

In [66]:
a.max()

6

In [67]:
a.sum()

21

In [69]:
a.mean() # átlag

3.5

In [70]:
a.std() # szórás

1.707825127659933

In [73]:
# Oszloponkénti statisztikák.
# A 0. dimenzió azaz a sorok mentén aggregálunk, ezért ez a dimenzió fog eltűnni.
a.sum(axis=0) # oszloponkénti összeg

array([5, 7, 9])

In [75]:
# Soronkénti statisztikák.
# A 1. dimenzió azaz az oszlopok mentén aggregálunk, ezért ez a dimenzió fog eltűnni.
a.max(axis=1) # soronkénti maximum

array([3, 6])

In [78]:
# Típuskonverzió.
b = a.astype('float32')
b

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

In [80]:
# Transzponálás.
print(a)
print(a.T)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [83]:
# A transzponálás nem végez másolást, csak egy új nézetet hoz létre az eredeti adattartalomra.
a.T[1, 0] = 20
a

array([[ 1, 20,  3],
       [ 4,  5,  6]])

In [86]:
# Hozzunk létre egy 12 elemű példatömböt!
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [87]:
# Átalakítás 2×6-ossá.
a.reshape((2, 6))

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [88]:
# Elég csak az egyik dimenzió méretét megadni, a másik helyére írhatunk (-1)-et.
a.reshape((2, -1))

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [89]:
# Átalakítás 4×3-assá.
a.reshape((-1, 3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [90]:
# Ha olyan méretet adunk meg, ahol az összelemszám nem jöhet ki 12-re, akkor hibaüzenetet kapunk.
a.reshape((5, -1))

ValueError: cannot reshape array of size 12 into shape (5,newaxis)

In [91]:
# Átalakítás 2×2×3-assá.
a.reshape((2, 2, 3))

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [92]:
# Az értékadás NumPy esetén sem végez másolást.
a = np.array([2, 3, 4])
b = a
b[0] = 200
a

array([200,   3,   4])

In [93]:
# Másolni a copy metódussal lehet.
a = np.array([2, 3, 4])
b = a.copy()
b[0] = 200
a

array([2, 3, 4])

In [7]:
# Keresés.
# Példa: Mely indexeknél találhatók az 5-nél kisebb elemek?
a = np.array([3, 10, 11, 4, 7, 8])
idxs = np.where(a < 5)[0]
idxs

array([0, 3])

In [99]:
a[idxs]

array([3, 4])

In [101]:
# Rendezés helyben.
a = np.array([3, 10, 11, 4, 7, 8])
a.sort()
a

array([ 3,  4,  7,  8, 10, 11])

In [103]:
# Rendezés új tömbbe.
a = np.array([3, 10, 11, 4, 7, 8])
b = np.sort(a)
print(a)
print(b)

[ 3 10 11  4  7  8]
[ 3  4  7  8 10 11]


Megjegyzés:
- NumPy tömbök rendezésére ne használjuk a standard sorted függvényt!
- Ugyanígy, NumPy tömbök esetén ne használjuk a standard math modul függvényeit!

In [108]:
# Rendezés csökkenő sorrendbe.
np.sort(a)[::-1]

array([11, 10,  8,  7,  4,  3])

In [110]:
# A rendezett tömb elemei mely indexeknél találhatók az eredeti tömbben?
idxs = a.argsort()
print(a)
print(idxs)

[ 3 10 11  4  7  8]
[0 3 4 5 1 2]


In [111]:
# A tömb rendezése az indextömb segítségével.
a[idxs]

array([ 3,  4,  7,  8, 10, 11])

In [113]:
# Van argmin és argmax függvény is.
a.argmax()

2

In [115]:
# Két vektor skaláris szorzata.
a = np.array([3, 4, 5])
b = np.array([2, 2, 2])
a @ b

24

In [117]:
# Mátrixszorzás.
A = np.array([[2, 3, 4],
              [5, 6, 7]])
A @ A.T

array([[ 29,  56],
       [ 56, 110]])

In [118]:
A.T @ A

array([[29, 36, 43],
       [36, 45, 54],
       [43, 54, 65]])

In [119]:
A @ A

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

#### [Broadcastolás](https://docs.scipy.org/doc/numpy/user/basics.broadcasting.html)
- A broadcastolás a különböző alakú operandusok kezelésére szolgál.
- Példa: 
```
A (4d tömb):        8 x 1 x 6 x 5
B (3d tömb):            7 x 1 x 5
Eredmény (4d tömb): 8 x 7 x 6 x 5
```

In [120]:
# Vektor szorzása skalárral.
a = np.array([2, 3, 4])
b = 10

# a: 3
# b: -

a * b

array([20, 30, 40])

In [121]:
# Példa nem broadcastolható tömbökre.
a = np.array([2, 3])
b = np.array([4, 5, 6])

# a: 2
# b: 3

a + b

ValueError: operands could not be broadcast together with shapes (2,) (3,) 

In [125]:
# Mátrix szorzása vektorral.
A = np.array([[3, 4, 5],
              [5, 6, 7]])
b = np.array([1, 2, 3])

# A: 2 3
# b: - 3

A * b # Oszloponkénti szorzás.

array([[ 3,  8, 15],
       [ 5, 12, 21]])

In [131]:
# Soronkénti szorzás.
A = np.array([[3, 4, 5],
              [5, 6, 7]])
b = np.array([1, 2])
(A.T * b).T

array([[ 3,  4,  5],
       [10, 12, 14]])