### 1. feladat

Hozzunk létre egy 3×3-as, csupa True logikai értéket tartalmazó, NumPy tömböt!

In [1]:
import numpy as np

In [2]:
# 1. megoldás
np.array([[True] * 3] * 3)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [3]:
# 2. megoldás
np.ones((3, 3), dtype='bool')

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

### 2. feladat

Írjuk ki a páratlan elemeket az alábbi 2 dimenziós NumPy tömbben!

In [4]:
b = np.array([[2, 3, 4], [5, 6, 7]])
print(b[b % 2 == 1])

[3 5 7]


### 3. feladat

Írjuk ki a 3-nál nagyobb elemeket az alábbi 2 dimenziós NumPy tömbben!

In [5]:
b = np.array([[2, 3, 4], [5, 6, 7]])
print(b[b > 3])

[4 5 6 7]


### 4. feladat

Írjuk ki az átlag feletti elemeket az alábbi NumPy tömbben!

In [6]:
b = np.array([1, 10, 2, 8, 3, 5, 9])
print(b[b > b.mean()])

[10  8  9]


### 5. feladat

Készítsünk programot, amely egyenletes eloszlás szerint generál 1000 db térbeli pontot az egységkockában, majd meghatározza az 1. ponttól legtávolabb eső pontot!

In [7]:
# pontok generálása
rs = np.random.RandomState(42)
P = rs.uniform(size=(1000, 3))
P

array([[0.37454012, 0.95071431, 0.73199394],
       [0.59865848, 0.15601864, 0.15599452],
       [0.05808361, 0.86617615, 0.60111501],
       ...,
       [0.80000348, 0.55270708, 0.39655368],
       [0.13171503, 0.86529576, 0.15727321],
       [0.30978786, 0.29004553, 0.87141403]])

In [8]:
# legtávolabbi pont kiszámítása, 1. megoldás

p = P[0]
dmax = 0
for pi in P:
    act = ((p[0] - pi[0])**2 + (p[1] - pi[1])**2 +(p[2] - pi[2])**2)**0.5
    if(act > dmax):
        dmax = act
        pmax = pi
print(pmax)

[0.89633582 0.01300192 0.08550853]


In [9]:
# legtávolabbi pont kiszámítása, 2. megoldás (vektorizálással)

# P: 1000 3
# p:    - 3

P[((P - p)**2).sum(axis=1).argmax()]

array([0.89633582, 0.01300192, 0.08550853])

In [10]:
# időigény összehasonlítás
def calc_max_1(P, p):
    dmax = 0
    for pi in P:
        act = ((p[0] - pi[0])**2 + (p[1] - pi[1])**2 +(p[2] - pi[2])**2)**0.5
        if(act > dmax):
            dmax = act
            pmax = pi
    return pmax

%timeit calc_max_1(P, p)

10.5 ms ± 391 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [11]:
%timeit P[((P - p)**2).sum(axis=1).argmax()]

213 µs ± 38.1 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


### 6. feladat

A [baseball.txt](baseball.txt) szövegfájl professzionális baseball játékosok testmagasságáról és testsúlyáról tartalmaz adatokat. Készítsünk programot, amely lineáris modellt ad a testsúly testmagasságból történő előrejelzésére! Részfeladatok:
- Határozzuk meg a minimális SSE (sum squared error) hibát adó modellparamétert!
- Adjunk becslést egy 180 cm magas játékos testsúlyára!

<img src="linreg_1d.jpg" width="600"></img>

In [12]:
# Adatok betöltése.
data = np.genfromtxt('baseball.txt', delimiter=',')
data

array([[188.,  82.],
       [188.,  98.],
       [183.,  95.],
       ...,
       [190.,  93.],
       [190.,  86.],
       [185.,  88.]])

In [13]:
# bemeneti vektor
x = data[:, 0]

# célvektor
y = data[:, 1]

In [14]:
# átlag kivonása
xm = x.mean()
ym = y.mean()
x -= xm
y -= ym

In [15]:
x

array([ 0.92836399,  0.92836399, -4.07163601, ...,  2.92836399,
        2.92836399, -2.07163601])

In [16]:
y

array([-9.50338819,  6.49661181,  3.49661181, ...,  1.49661181,
       -5.50338819, -3.50338819])

In [17]:
# Optimális modellparaméter.
w = (x @ y) / (x @ x)
w

0.8561919786085516

In [18]:
# Becslés egy 180 cm magas játékos testsúlyára.
(180 - xm) * w + ym

85.44871016095308

### 7. feladat

Készítsen függvényt, amely egy adott `n` pozitív egész számra (mint bemenő paraméter) eredményként előállít egy olyan négyzetes mátrixt (mint `numpy` tömböt), amelyik négy db `n*n`-es részmátrixból áll úgy, hogy a bal felső részmátrix 1-eseket, a jobb felső 2-eseket, a bal alsó 3-asokat, és a jobb alsó 4-eseket tartalmazzon!

Példák:
```
n = 1             n = 2                 n = 3      
1 2               1 1 2 2               1 1 1 2 2 2
3 4               1 1 2 2               1 1 1 2 2 2
                  3 3 4 4               1 1 1 2 2 2
                  3 3 4 4               3 3 3 4 4 4
                                        3 3 3 4 4 4
                                        3 3 3 4 4 4
```

### 8. feladat

Készítsünk függvényt, amely egy paraméterként kapott mátrix (mint kétdimenziós numpy tömb) alapján előállít egy új mátrixot (mint kétdimenziós numpy tömböt), ami már nem tartalmazza a mátrix egy adott  indexű oszlopát!

Elvárt működés:
```
 Input                        Output

 A mátrix                     A mátrix
 1.0, 2.0, 3.0                1.0, 3.0
 4.0, 5.0, 6.0                4.0, 6.0
 
 A törlendő oszlop indexe
 1
```